debug: False
seed: 123
dataset : "nuscenes"
working_dir : "output/pretrain/nuscenes_minkunet/"
# if set to True, use cylindrical coordinates, otherwise use cartesian
cylindrical_coordinates : True
# size of the voxel in each dimension for cartesian coordinates,
# and in rho and z for cylindrical (angular is always 1°)
voxel_size : 0.1
batch_size : 32
# learning rate
lr : 1.6
sgd_momentum : 0.9
sgd_dampening : 0.1
weight_decay : 0.0001
num_epochs : 50
# used in superpixel loss only, drop points and pixels from the computation of the loss
dropout : 0.
# number of GPUs and CPU threads to use
num_gpus : 4 # 4
num_threads : 32 # 32
kernel_size : 3
model_n_out : 64
bn_momentum : 0.05
crop_size : [224, 416]
crop_ratio : [1.5555555555555556, 1.8888888888888888]
model_points : "minkunet" # choose from [minkunet18, minkunet, minkunet50, minkunet101]
image_weights : "moco_v2"
# which image encoder to use (only imagenet is available with resnet18)
images_encoder : "resnet50"
# which image decoder to use
# 'bilinear', 'unet', 'fpn', 'semseg', 'nnfe', 'dilation', 'ppkt'
decoder : "dilation"
# temperature parameter in the InfoNCE loss
NCE_temperature : 0.07
# number of positive matches in the InfoNCE loss
num_matches : 4096
# whether to use the true validation set or the custom parametrization set
training : "parametrize"
# transformations to apply to the clouds
transforms_clouds : ["Rotation", "FlipAxis"]
# transformations to apply to both the clouds and the images among:
# 'FlipHorizontal', 'DropCuboids', 'ResizedCrop'
transforms_mixed : ["DropCuboids", "ResizedCrop", "FlipHorizontal"]
# which losses to use (note that multiple losses will be summed)
losses : ["loss_superpixels_average"]  # for vallina NCE use "loss_nce"

superpixels_type : "dinov2"
superpixels_path : '{Your_superpixel_path}/dino_mask_png/nuscenes'
superpixel_size : 150
ignored_label: -1

# which kind of superpixels to use
#superpixels_type : "grounding_sam"
#superpixels_path : '/data2/share/superpixels_GSAM'
#superpixel_size : 30
#ignored_label: 255

#superpixels_type : "san"
#superpixels_path : '/data2/share/superpixels_SAN'
#superpixel_size : 30
#ignored_label: 255

#superpixels_type : "seem"
#superpixels_path : '/data2/share/superpixels_seem'
#superpixel_size : 48 # seem
#ignored_label: 0

#superpixels_type : "oneformer"
#superpixels_path : '/data2/share/superpixels_OneFormer_cityscapes_semantic'
#superpixel_size : 19 # oneformer
#ignored_label: 255

# only keep 1 in dataset_skip_step training examples (here use 100% of the data)
dataset_skip_step : 1
# path to weights to continue a previous training
resume_path : Null

decoupled_head: False
normalize_intensity: False
use_vse: True
sweeps_pair_list_path : '/data2/share/stf/sweeps_flitered_by_dino_mIoU.pkl'
sweeps_skip_step: 1

# WARNING: DO NOT CHANGE THE FOLLOWING PARAMETERS
# ===============================================
normalize_features : True